### ISSUE TITLE
Consider unpinning the version of`jsdom` required by `h2x-parse`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [smooth-code/h2x#7]
`jsdom` is a pretty big package (a couple megabytes before transitive dependencies).  Pinning it to a specific version prevents it from deduping with other versions of `jsdom`.  For example, it currently cannot dedupe with the version required by `jest`.

**Comment by neoziro** [comment]
Yes but in recent version, JSDOM protects objects and it requires a lot of work in h2x to make it work with new JSDOM version.
